params:
  expertises:
    thumbnail:
      desktop: "414x177"
      mobile: "300x129"
      scrollsnap: "240x103"
    image:
      desktop: "300x"
      mobile: "300x"
  offices:
    thumbnail:
      desktop: "414x414"
      mobile: "300x300"
      scrollsnap: "240x103"
    image:
      desktop: "300x"
      mobile: "198x"
