params:
  expertises:
    thumbnail:
      desktop: "414x177"
      mobile: "300x129"
      scrollsnap: "240x103"
    image:
      desktop: "300x"
      mobile: "300x"
  offices:
    thumbnail:
      desktop: "414x414"
      mobile: "300x300"
      scrollsnap: "240x103"
    image:
      desktop: "300x"
      mobile: "198x"
  persons:
    thumbnail:
      desktop: "100x100"
      mobile: "100x100"
    image:
      desktop: "300x"
      mobile: "198x"
    post:
      desktop: "50x50"
      mobile: "50x50"
    publication:
      desktop: "50x50"
      mobile: "50x50"